### ISSUE TITLE
Use shebangs the recommended way.

### ISSUE THREAD

**Issue by ericonr** [fohtla/Fallout3Terminal#1]
You should probably use the shebang (that first line on the file, which tells the operating system how to execute the file) as

```bash
#!/usr/bin/env bash
```

This way, anyone who uses your script but for some reason stores their preferred version of bash somewhere else, can still run it with their preferred version.

**Comment by ericonr** [comment]
Seeing as you are already using a shebang, and recommend making the script executable, you could make it executable and use git to store that attribute of the file, so

**Comment by ericonr** [comment]
All that said, awesome project!

**Comment by longhorn09** [comment]
And maybe rename `terminalscript` to `terminalscript.sh` is kind of standard, to denote shell script.
