### ISSUE TITLE
Mac OS instructions

### ISSUE THREAD

**Issue by iFloris** [fohtla/Fallout3Terminal#11]
Hello, thanks for making this.
There are no instructions to run this on a Mac, but this can easily be done.
My method is as follows:
1. Have homebrew installed
2. `brew install sox pv`
3. `brew cask install cool-retro-term`
4. `git clone https://github.com/fohtla/Fallout3Terminal`
5. `/Applications/cool-retro-term.app/Contents/MacOS/cool-retro-term --fullscreen --noclose -e bash $HOME/Fallout3Terminal/terminalscript`

**Comment by fohtla** [comment]
Have you tested this out? I have next to 0 experience with anything Mac, and I would happily add this to the readme if it works perfectly. I appreciate the help for a novice like myself!

**Comment by iFloris** [comment]
Hello @fohtla yes these are the steps I used to get it working on my Mac :)

**Comment by fohtla** [comment]
Thanks for the quick reply! I have added it to the readme, it would be highly appreciated if you could check it for errors! Thanks again :)

**Comment by iFloris** [comment]
Hello @fohtla thanks a lot, that looks fine to me. One thing, my instructions assume that the user is using ~ to run things from.
