### ISSUE TITLE
Request: specify LICENSE

### ISSUE THREAD

**Issue by mcorossigo** [fohtla/Fallout3Terminal#7]
Hello @fohtla 

As many others, I'm coming from Reddit.
Awesome work here!

I was thinking about expanding the entries with ideas and stuff, but since we live in interesting times, I have to ask:

do you mind licensing the project under a permissive license (preferably MIT) so that people can freely fork or contribute?

Thank you!

**Comment by fohtla** [comment]
I would be happy to let anyone do as they please with this! I did not know about licensing so I skipped that part while making the repository. I have done research and you'd be pleased to know that I have added an MIT license. Go to town on it buddy! Enjoy :)
